#!/usr/bin/env python3
"""Pack Alpine 9p images into ucdVscode/alpine-vfs.js for file:// UCDVSC.

Usage (after Alpine guest images exist under v86/images/):
  python3 src/offline/make-alpine-vfs.py
"""
from __future__ import annotations

import base64
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]  # UCD/
V86 = REPO / "v86"
OUT_VFS = REPO / "ucdVscode" / "alpine-vfs.js"
IMAGES = V86 / "images"
FLAT = IMAGES / "alpine-rootfs-flat"
FS_JSON = IMAGES / "alpine-fs.json"


def write_vfs_pack() -> None:
    if not FS_JSON.is_file() or not FLAT.is_dir():
        raise SystemExit(
            f"missing Alpine images under {IMAGES}\n"
            "  run: bash src/guest/build-alpine.sh"
        )

    files: list[tuple[str, pathlib.Path]] = [
        ("images/alpine-fs.json", FS_JSON),
    ]
    for p in sorted(FLAT.iterdir()):
        if p.is_file():
            files.append((f"images/alpine-rootfs-flat/{p.name}", p))

    total = sum(p.stat().st_size for _, p in files)
    print(
        f"packing {len(files)} files ({total / 1024 / 1024:.1f} MiB raw) → {OUT_VFS.name} …",
        flush=True,
    )

    OUT_VFS.parent.mkdir(parents=True, exist_ok=True)
    with OUT_VFS.open("w", encoding="utf-8") as out:
        out.write(
            "/* auto-generated by src/offline/make-alpine-vfs.py — do not edit */\n"
            "(function (g) {\n"
            "  var m = (g.__V86_VFS_B64__ = g.__V86_VFS_B64__ || {});\n"
        )
        for i, (key, path) in enumerate(files, 1):
            data = base64.b64encode(path.read_bytes()).decode("ascii")
            out.write(f"  m[{json.dumps(key)}] = {json.dumps(data)};\n")
            if key.startswith("images/alpine-rootfs-flat/"):
                base = key.rsplit("/", 1)[-1]
                out.write(f"  m[{json.dumps(base)}] = m[{json.dumps(key)}];\n")
            if i % 200 == 0 or i == len(files):
                print(f"  {i}/{len(files)}", flush=True)
        out.write("  g.__V86_VFS_READY__ = true;\n")
        out.write("})(typeof window !== 'undefined' ? window : globalThis);\n")

    print(f"wrote {OUT_VFS} ({OUT_VFS.stat().st_size / 1024 / 1024:.1f} MiB)", flush=True)


if __name__ == "__main__":
    write_vfs_pack()
